CREATE TABLE Users (
Id INT AUTO_INCREMENT PRIMARY KEY,
Username VARCHAR(255) NOT NULL UNIQUE,
PasswordHash VARCHAR(255) NOT NULL,
Salt VARCHAR(255) NOT NULL,
CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE Workouts (
Id INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
Description TEXT,
DurationMinutes INT NOT NULL,
Difficulty ENUM('Easy', 'Medium', 'Hard'),
CreatedBy INT,
UpdatedBy INT,
CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



CREATE TABLE Movements (
Id INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
Description TEXT,
WorkoutId INT,
CreatedBy INT,
UpdatedBy INT,
CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (WorkoutId) REFERENCES Workouts(Id)
);


CREATE TABLE BodyRegions (
Id INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(255) NOT NULL
);


CREATE TABLE WorkoutBodyRegions (
WorkoutId INT,
BodyRegionId INT,
PRIMARY KEY (WorkoutId, BodyRegionId),
FOREIGN KEY (WorkoutId) REFERENCES Workouts(Id),
FOREIGN KEY (BodyRegionId) REFERENCES BodyRegions(Id)
);
